[package]
name = "aptosDAS"
version = "1.0.0"
authors = []

[addresses]
CAFE = "0x2c2b6f259066f1653c6610b6ab8e2dfafbe8ff62ab61d8a563f48c1f8fb23bfd"

[dev-addresses]



[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "46bf426662e4dc1b9e7317fc7fc66594bfaf6edb"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-token-objects"
[dev-dependencies]
